### ISSUE TITLE
Create a Download CV option

### ISSUE THREAD

**Issue by sazzadsazib** [sazzadsazib/portfolio#11]
**Is your feature request related to a problem? Please describe.**

No, Want to have a option to download CV from my PWA !!

**Describe the solution you'd like**
Update A new Section for downloading CV

**Describe alternatives you've considered**
 have this in Profile Section

**Additional context**
Nothing :)

**Comment by josephshin93** [comment]
I would like to help with this. I do have some questions about the enhancement.

- Based on your description of the solution, I generated these mock ups of the side nav bar and new CV download page. Are these consistent with what you were imagining?
![new-sidebar-mockup](https://user-images.githubusercontent.com/15806388/59162309-a0563600-8abc-11e9-8b43-fdba02c0c715.png)
![cv-dl-page](https://user-images.githubusercontent.com/15806388/59162313-a3e9bd00-8abc-11e9-8334-ce8a1c2e2c9b.png)
- Do you intend for this download feature to be implemented entirely on the front-end?

**Comment by sazzadsazib** [comment]
Hey @josephshin93 , thanks for the interest,
* Yes I intend to do this is front-end for now because haven't used any backend so far

For Nav bar something like this,
![cv 1-mockup](https://user-images.githubusercontent.com/8937268/59173214-b243e180-8b6d-11e9-91f2-5b742c921c3a.png)

For Preview and download something like this,
![cv 2-mockup](https://user-images.githubusercontent.com/8937268/59173232-c982cf00-8b6d-11e9-9c37-282756afbfb6.png)

this is related to Issue #13 too ,

Later on if we move on to a backend then we can have more generic such as login system and upload personal cv from settings menu (lets keep this for future :) )

thanks :)

**Comment by josephshin93** [comment]
I see. Your designs are clean and intuitive. I went ahead and dove into some development earlier, hopefully the changes will not conflict with development you have already done. I have essentially implemented what you see in the mock ups that I posted above including a simple, "front-end only" download functionality. I can try to push the branch I have been working on to this repository so you can see the progress I made and future changes I can make to match the mock ups you've provided.

**Comment by sazzadsazib** [comment]
Sure Send a PR

**Comment by sazzadsazib** [comment]
#15
